import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { setMenu } from '@/store/slices/menuSlice';

const useMenuItems = () => {
  const dispatch = useDispatch();
  const prefetchMenuItems = useSelector((state) => state.menu.items);

  useEffect(() => {
    if (prefetchMenuItems.length !== 0) return;
    dispatch(setMenu(menuItems));
    
  }, [dispatch, prefetchMenuItems]);

};

export default useMenuItems;

const menuItems = [
  {
    id: '1',
    name: 'Spaghetti with Beef',
    description: 'A delicious spaghetti dish with tender beef and a rich tomato sauce.',
    price: 12.99,
    image_url: '/menu/italian/spaghetti-with-beef.png',
    cuisine: 'Italian',
    category: 'Main Course',
    star_rating: 4.5,
    rating_count: 120,
    dietary_preferences: ['Gluten-Free'],
  },
  {
    id: '2',
    name: 'Margherita Pizza',
    description: 'Classic Italian pizza with fresh tomatoes, mozzarella, and basil.',
    price: 11.99,
    image_url: '/menu/italian/margherita-pizza.png',
    cuisine: 'Italian',
    category: 'Main Course',
    star_rating: 4.7,
    rating_count: 150,
    dietary_preferences: ['Vegetarian'],
  },
  {
    id: '3',
    name: 'Fettuccine Alfredo',
    description: 'Creamy Alfredo sauce served over fettuccine pasta.',
    price: 13.99,
    image_url: '/menu/italian/fettuccine-alfredo.png',
    cuisine: 'Italian',
    category: 'Main Course',
    star_rating: 4.3,
    rating_count: 95,
    dietary_preferences: ['Vegetarian'],
  },
  {
    id: '4',
    name: 'Vegan Burger',
    description: 'A hearty burger made with a plant-based patty, served with fresh veggies.',
    price: 10.99,
    image_url: '/menu/american/vegan-burger.png',
    cuisine: 'American',
    category: 'Main Course',
    star_rating: 4.8,
    rating_count: 200,
    dietary_preferences: ['Vegan', 'Gluten-Free'],
  },
  {
    id: '5',
    name: 'Caesar Salad',
    description: 'A classic Caesar salad with crispy lettuce, croutons, and a creamy dressing.',
    price: 8.99,
    image_url: '/menu/american/caesar-salad.png',
    cuisine: 'American',
    category: 'Appetizer',
    star_rating: 3.0,
    rating_count: 80,
    dietary_preferences: ['Gluten-Free'],
  },
  {
    id: '6',
    name: 'Mac and Cheese',
    description: 'Creamy mac and cheese topped with crispy breadcrumbs.',
    price: 9.99,
    image_url: '/menu/american/mac-and-cheese.png',
    cuisine: 'American',
    category: 'Side Dish',
    star_rating: 4.4,
    rating_count: 110,
    dietary_preferences: ['Vegetarian'],
  },
  {
    id: '7',
    name: 'Buffalo Wings',
    description: 'Spicy buffalo wings served with blue cheese dipping sauce.',
    price: 12.49,
    image_url: '/menu/american/buffalo-wings.png',
    cuisine: 'American',
    category: 'Appetizer',
    star_rating: 4.6,
    rating_count: 90,
    dietary_preferences: [],
  },
  {
    id: '8',
    name: 'Tacos',
    description: 'Soft tortillas filled with seasoned beef, lettuce, and cheese.',
    price: 9.49,
    image_url: '/menu/mexican/tacos.png',
    cuisine: 'Mexican',
    category: 'Main Course',
    star_rating: 4.5,
    rating_count: 130,
    dietary_preferences: ['Gluten-Free'],
  },
  {
    id: '9',
    name: 'Nacho Chips',
    description: 'Fresh guacamole served with crispy tortilla chips.',
    price: 6.99,
    image_url: '/menu/mexican/nacho-chips.png',
    cuisine: 'Mexican',
    category: 'Appetizer',
    star_rating: 2.7,
    rating_count: 60,
    dietary_preferences: ['Vegan', 'Gluten-Free'],
  },
  {
    id: '10',
    name: 'Beef Burrito',
    description: 'A large burrito stuffed with beef, rice, beans, and cheese.',
    price: 11.49,
    image_url: '/menu/mexican/beef-burrito.png',
    cuisine: 'Mexican',
    category: 'Main Course',
    star_rating: 4.0,
    rating_count: 120,
    dietary_preferences: [],
  },
  {
    id: '11',
    name: 'Sushi Platter',
    description: 'An assortment of fresh sushi including tuna, salmon, and shrimp.',
    price: 19.99,
    image_url: '/menu/japanese/sushi-platter.png',
    cuisine: 'Japanese',
    category: 'Main Course',
    star_rating: 4.8,
    rating_count: 140,
    dietary_preferences: ['Gluten-Free'],
  },
  {
    id: '13',
    name: 'Ramen',
    description: 'Traditional Japanese noodle soup with pork, egg, and vegetables.',
    price: 13.49,
    image_url: '/menu/japanese/ramen.png',
    cuisine: 'Japanese',
    category: 'Main Course',
    star_rating: 4.7,
    rating_count: 95,
    dietary_preferences: [],
  },
  {
    id: '14',
    name: 'Chicken Tikka Masala',
    description: 'Tender chicken in a creamy tomato-based sauce, served with rice.',
    price: 14.99,
    image_url: '/menu/indian/chicken-tikka-masala.png',
    cuisine: 'Indian',
    category: 'Main Course',
    star_rating: 5.0,
    rating_count: 180,
    dietary_preferences: ['Gluten-Free'],
  },
  {
    id: '15',
    name: 'Vegetable Samosas',
    description: 'Crispy pastry filled with spiced vegetables, served with chutney.',
    price: 7.99,
    image_url: '/menu/indian/vegetable-samosas.png',
    cuisine: 'Indian',
    category: 'Appetizer',
    star_rating: 4.4,
    rating_count: 85,
    dietary_preferences: ['Vegan'],
  },
  {
    id: '16',
    name: 'Naan Bread',
    description: 'Soft and fluffy naan bread, perfect for dipping in curries.',
    price: 3.99,
    image_url: '/menu/indian/naan-bread.png',
    cuisine: 'Indian',
    category: 'Side Dish',
    star_rating: 3.6,
    rating_count: 70,
    dietary_preferences: ['Vegetarian'],
  },
  {
    id: '17',
    name: 'Kung Pao Chicken',
    description: 'Stir-fried chicken with peanuts, vegetables, and chili peppers.',
    price: 12.49,
    image_url: '/menu/chinese/kung-pao-chicken.png',
    cuisine: 'Chinese',
    category: 'Main Course',
    star_rating: 4.6,
    rating_count: 110,
    dietary_preferences: ['Gluten-Free'],
  },
  {
    id: '18',
    name: 'Vegetable Spring Rolls',
    description: 'Crispy spring rolls filled with seasoned vegetables.',
    price: 6.49,
    image_url: '/menu/chinese/vegetable-spring-rolls.png',
    cuisine: 'Chinese',
    category: 'Appetizer',
    star_rating: 4.3,
    rating_count: 80,
    dietary_preferences: ['Vegan'],
  },
  {
    id: '19',
    name: 'Sweet and Sour Pork',
    description: 'Crispy pork in a tangy sweet and sour sauce.',
    price: 13.49,
    image_url: '/menu/chinese/sweet-and-sour-pork.png',
    cuisine: 'Chinese',
    category: 'Main Course',
    star_rating: 4.5,
    rating_count: 100,
    dietary_preferences: [],
  },
  {
    id: '20',
    name: 'Coq au Vin',
    description: 'Chicken braised with wine, mushrooms, and onions.',
    price: 17.99,
    image_url: '/menu/french/coq-au-vin.png',
    cuisine: 'French',
    category: 'Main Course',
    star_rating: 4.8,
    rating_count: 95,
    dietary_preferences: [],
  },
  {
    id: '21',
    name: 'Ratatouille',
    description: 'A vegetable medley of eggplant, zucchini, and peppers in a rich tomato sauce.',
    price: 10.99,
    image_url: '/menu/french/ratatouille.png',
    cuisine: 'French',
    category: 'Main Course',
    star_rating: 4.7,
    rating_count: 75,
    dietary_preferences: ['Vegan'],
  },
  {
    id: '22',
    name: 'Crème Brûlée',
    description: 'A rich custard topped with a layer of caramelized sugar.',
    price: 7.49,
    image_url: '/menu/french/creme-brulee.png',
    cuisine: 'French',
    category: 'Dessert',
    star_rating: 4.9,
    rating_count: 60,
    dietary_preferences: ['Vegetarian'],
  },
  {
    id: '23',
    name: 'Greek Salad',
    description: 'A refreshing salad with cucumbers, tomatoes, feta cheese, and olives.',
    price: 9.49,
    image_url: '/menu/mediterranean/greek-salad.png',
    cuisine: 'Mediterranean',
    category: 'Appetizer',
    star_rating: 4.6,
    rating_count: 100,
    dietary_preferences: ['Vegetarian', 'Gluten-Free'],
  },
  {
    id: '24',
    name: 'Falafel Wrap',
    description: 'Crispy falafel wrapped in pita bread with tahini sauce.',
    price: 10.49,
    image_url: '/menu/mediterranean/falafel-wrap.png',
    cuisine: 'Mediterranean',
    category: 'Main Course',
    star_rating: 4.4,
    rating_count: 110,
    dietary_preferences: ['Vegan'],
  },
  {
    id: '25',
    name: 'Baklava',
    description: 'A sweet pastry made with layers of filo dough, nuts, and honey.',
    price: 6.99,
    image_url: '/menu/mediterranean/baklava.png',
    cuisine: 'Mediterranean',
    category: 'Dessert',
    star_rating: 5.0,
    rating_count: 90,
    dietary_preferences: ['Vegetarian'],
  },
];
